### ISSUE TITLE
Non-HT 4-core CPU - Q9650 detected as 2-core w/4 threads (HT?)

### ISSUE THREAD

**Issue by 01e3** [memtest86plus/memtest86plus#125]
Core2 Quad Q9650 (Yorkfield, 45nm) - family: 0x6, model: 0x17, stepping: 0xa detected as 2 Cores, 4 Threads:

![image](https://user-images.githubusercontent.com/105136494/180451839-518323c2-db2c-4edb-a243-43e5e5392f65.png)

```
# egrep -B1 "(core|processor)" < /proc/cpuinfo
processor       : 0
--
siblings        : 4
core id         : 0
cpu cores       : 4
--

processor       : 1
--
siblings        : 4
core id         : 1
cpu cores       : 4
--

processor       : 2
--
siblings        : 4
core id         : 2
cpu cores       : 4
--

processor       : 3
--
siblings        : 4
core id         : 3
cpu cores       : 4
```

**Comment by x86fr** [comment]
SMT issue should be solved with latest commit.

**Comment by 01e3** [comment]
cf156adc4a0066751536c9d1a5eeef463c314eac still shows 2C/4T on Q9650:
![image](https://user-images.githubusercontent.com/105136494/180624417-3515adac-0533-4f85-a7e8-0ac486187192.png)

**Comment by x86fr** [comment]
OK it's a different issue vs #129. Will push another patch for Yorkfield.

**Comment by x86fr** [comment]
Yorkfield have a max cpuid set at 0xD but 0xB doesn't exist because they don't support x2APIC and the advanced topology. That's probably the issue.

Can you try with this ?

```
--- a/system/cpuid.c
+++ b/system/cpuid.c
@@ -181,7 +181,7 @@ void cpuid_init(void)
        case 'G':
         if (cpuid_info.vendor_id.str[7] == 'T') break; // Transmeta
         // Intel
-        if (cpuid_info.max_cpuid >= 0xB) {
+        if (cpuid_info.max_cpuid >= 0xB && cpuid_info.flags.x2apic) {

             // Populate Hybrid Status (CPUID 7.EDX[15]) for Alder Lake+
             cpuid(0x7, 0, &reg[0], &reg[1], &reg[2], &reg[3]);


```

**Comment by 01e3** [comment]
With the above patch, Memtest reports 4 cores, 4 threads.

**Comment by x86fr** [comment]
Ok, I will push it later today.

**Comment by x86fr** [comment]
Pushed to main
