### ISSUE TITLE
USB keyboard not working on MSI KT4AV (MS-6712) with UHCI controller

### ISSUE THREAD

**Issue by debrouxl** [memtest86plus/memtest86plus#33]
At the time of this writing, the UHCI code contains the "This is currently untested and very unlikely to work out of the box." comment. I don't know about other MBs, but I have another MB, for the Athlon XP / DDR1 generation, on which the USB keyboard does not work :)

Namely, when passing `keyboard=usb` or `keyboard=buggy-usb`, all three Num Lock, Caps Lock, Scroll Lock LEDs of the usual Logitech K120 are lit, and that's pretty much it. Rebooting the computer after the test starts is done through the reset button. I haven't enabled the USB logging code.

Not that it matters to me in practice, since that nearly two decade old MS-6712 version 10A MB model, like pretty much all MBs of that area, has a PS/2 keyboard port, and I have a PS/2 keyboard.

The MB also has an EHCI controller, but all of the 2 x 2 USB ports on the back and the 2 USB ports on the diags LEDs +USB ports combo are connected to the UHCI controllers, 2 ports per controller, according to Linux `lsusb` when I cycle the keyboard through the ports.

```
00:00.0 Host bridge: VIA Technologies, Inc. VT8377 [KT400/KT600 AGP] Host Bridge (rev 80)
00:01.0 PCI bridge: VIA Technologies, Inc. VT8237/CX700/VX700-Series PCI to PCI Bridge
00:10.0 USB controller: VIA Technologies, Inc. VT82xx/62xx/VX700/8x0/900 UHCI USB 1.1 Controller (rev 80)
00:10.1 USB controller: VIA Technologies, Inc. VT82xx/62xx/VX700/8x0/900 UHCI USB 1.1 Controller (rev 80)
00:10.2 USB controller: VIA Technologies, Inc. VT82xx/62xx/VX700/8x0/900 UHCI USB 1.1 Controller (rev 80)
00:10.3 USB controller: VIA Technologies, Inc. USB 2.0 EHCI-Compliant Host-Controller (rev 82)
00:11.0 ISA bridge: VIA Technologies, Inc. VT8235 ISA Bridge
00:11.1 IDE interface: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 06)
00:11.5 Multimedia audio controller: VIA Technologies, Inc. VT8233/A/8235/8237 AC97 Audio Controller (rev 50)
00:12.0 Ethernet controller: VIA Technologies, Inc. VT6102/VT6103 [Rhine-II] (rev 74)

00:10.0 0c03: 1106:3038 (rev 80)
00:10.1 0c03: 1106:3038 (rev 80)
00:10.2 0c03: 1106:3038 (rev 80)
00:10.3 0c03: 1106:3104 (rev 82)
```

**Comment by martinwhitaker** [comment]
You should have got the message "This controller type is not supported yet" during the scan for USB keyboards. The UHCI driver code is not currently included in the build.

I don't have any hardware containing a UHCI controller. I was going to see what I could do with QEMU, but it was low down my priority list - hardware that old usually supports USB legacy keyboard emulation.

**Comment by martinwhitaker** [comment]
> I didn't see any form of USB scan, BTW.

That's probably because Sam has changed the default value of `pause_at_start`. It likely went past too fast for you to see.

**Comment by martinwhitaker** [comment]
I've fixed some bugs in the UHCI driver and enabled it. It works in QEMU. Please give it a try on real hardware.

**Comment by x86fr** [comment]
Will try later today ;)

**Comment by debrouxl** [comment]
I should be able to try it on real hardware over the week-end.

**Comment by x86fr** [comment]
On 3 motherboards, it detects a device but not a keyboard:

![IMG_2392](https://user-images.githubusercontent.com/38105886/162327636-f43ab6c3-a714-44f5-aa37-b01f542943fc.jpg)

It is the keyboard because the device disappears if I unplug the keyboard.

Quick debug log:

```
in find_attached_usb_keyboards(...) *FAIL BECAUSE*
 -> return false at hcd->methods->assign_address(...) *FAIL BECAUSE*
   -> return true at hcd->methods->setup_request(...)
   -> return false at hcd->methods->get_data_request(...) *FAIL*
```

Looking at the code...

**Comment by martinwhitaker** [comment]
Having looked at the Linux driver, I've made a few adjustments to the controller initialisation. Please test to see if that has made any difference.

If not, is the failure occurring on the first call to `get_data_request()` or the second call? (before you edited it, your comment suggested it was the second call).

This patch should print out some diagnostic information when the `get_data_request()` fails:
````
--- a/system/uhci.c
+++ b/system/uhci.c
@@ -297,6 +297,12 @@ static uint16_t get_uhci_done(workspace_t *ws)
 
     uint16_t status = inw(UHCI_USBSTS) & (UHCI_USBSTS_INT | UHCI_USBSTS_ERR);
     if (status != 0) {
+       if (status & UHCI_USBSTS_ERR) {
+            uintptr_t td_addr = ws->qh[0].qe_link_ptr;
+            uhci_td_t *td = (uhci_td_t *)td_addr;
+            print_usb_info("transfer failed TD %08x status %08x token %08x",
+                           td_addr, (uintptr_t)td->control_status, (uintptr_t)td->token);
+       }
         outw(UHCI_USBSTS_INT | UHCI_USBSTS_ERR, UHCI_USBSTS);
         write32(&ws->qh[0].qe_link_ptr, UHCI_LP_TERMINATE);
     }
````

**Comment by x86fr** [comment]
Still not detected. :-/

I first thought it was the second call but I missed a goto, so it's the first call that fail.

Added the debug code

```
...
Found UHCI controller 8086:24d4 at 0000ef20 size ffff0020 in I/O space
transfer failed TD 0009d490 status 00450007 token 00e0002d
Found 1 device, 0 keyboards
...

```

**Comment by martinwhitaker** [comment]
The device speed bit wasn't being set in the transfer descriptor. I've pushed a fix for that, which should help if your keyboard is a low speed device.

**Comment by x86fr** [comment]
Keyboard still not detected **BUT** the communication is now fine and the issue is different

```
in find_attached_usb_keyboards(...) *FAIL BECAUSE*
 -> return true at (new_num_keyboards == old_num_keyboards) [0==0] *PASS BECAUSE*
   -> new_num_keyboards is set to 0 at get_keyboard_info_from_descriptors(...) *SET BECAUSE*
     -> return true at (if (next_ptr < (curr_ptr + 2) || next_ptr > tail_ptr)) *PASS BECAUSE*
       -> next_ptr = 0x9d009 
       -> curr_ptr = 0x9d009
       -> tail_ptr = 0x9d03b
       -> header->length = 0
```

**Comment by martinwhitaker** [comment]
Some progress :-)

Could you run again with this patch that displays the descriptors read back from the device:
````
--- a/system/usbhcd.c
+++ b/system/usbhcd.c
@@ -521,6 +521,14 @@ bool find_attached_usb_keyboards(const usb_hcd_t *hcd, const usb_hub_t *hub, int
     usb_device_desc_t *device = (usb_device_desc_t *)hcd->ws->data_buffer;
     bool is_hub = (device->class == USB_CLASS_HUB);
 
+    uint8_t *db = hcd->ws->data_buffer;
+    print_usb_info("device desc: length %i", hcd->ws->data_length);
+    for (int i = 0; i < (int)hcd->ws->data_length; i += 8) {
+        print_usb_info("%02x %02x %02x %02x %02x %02x %02x %02x",
+                       (uintptr_t)db[i+0], (uintptr_t)db[i+1], (uintptr_t)db[i+2], (uintptr_t)db[i+3],
+                       (uintptr_t)db[i+4], (uintptr_t)db[i+5], (uintptr_t)db[i+6], (uintptr_t)db[i+7]);
+    }
+
     // Fetch the descriptors for the first configuration into the data transfer buffer. In theory a keyboard device
     // may have more than one configuration and may only support the boot protocol in another configuration, but
     // this seems unlikely in practice. A hub should only ever have one configuration.
@@ -528,6 +536,12 @@ bool find_attached_usb_keyboards(const usb_hcd_t *hcd, const usb_hub_t *hub, int
     if (config_num == 0) {
         return false;
     }
+    print_usb_info("config desc: length %i", (int)hcd->ws->data_length);
+    for (int i = 0; i < (int)hcd->ws->data_length; i += 8) {
+        print_usb_info("%02x %02x %02x %02x %02x %02x %02x %02x",
+                       (uintptr_t)db[i+0], (uintptr_t)db[i+1], (uintptr_t)db[i+2], (uintptr_t)db[i+3],
+                       (uintptr_t)db[i+4], (uintptr_t)db[i+5], (uintptr_t)db[i+6], (uintptr_t)db[i+7]);
+    }
 
     if (is_hub) {
         usb_hub_t new_hub;
````

**Comment by x86fr** [comment]
![image](https://user-images.githubusercontent.com/38105886/162637624-7074c751-8fbd-499d-8f2f-26587f2ed0fd.jpeg)

**Comment by martinwhitaker** [comment]
The UHCI spec doesn't make this clear, but other sources show that the UHCI expects the driver software to split the data transfers into individual USB packets (whereas all the other USB controllers do that for you). So because the maximum packet size for a low speed device is 8 bytes, the transfers are stopping after 8 bytes instead of transferring the full descriptors. I'll try to fix the driver for that tomorrow.

**Comment by martinwhitaker** [comment]
I've pushed a fix for multi-packet transfers. Please test again.

**Comment by x86fr** [comment]
It works! Congratulation :)

**Comment by debrouxl** [comment]
Alright, thanks :)
I should be able to test tomorrow on my side as well.

**Comment by debrouxl** [comment]
It's much better indeed: the keyboard detection on UHCI now works on my side as well, and I can use the USB keyboard to enter / exit the config menu, or lock / unlock scroll. Good work :)
That works for a little while, then the keyboard goes unresponsive. This new, more minor issue, is reproducible. I'll try to determine whether it's a matter of time limit, rate limit or number of keypresses.

**Comment by debrouxl** [comment]
It looks like a rate-related issue: if I wait for long enough between two keypresses, I can press Space 40+ times successfully without the USB keyboard going unresponsive, whereas if I don't (queue 2-3 keypresses between two steps of the memory test), the keyboard goes unresponsive quicly, in 3-4 keypresses.

**Comment by debrouxl** [comment]
I tested 3 keyboards plugged simultaneously, one on every UHCI controller of the KT4AV: MS Wired Keyboard 600, HP KU-0316, Logitech K120. They're correctly detected and all three work. I haven't tested for rate-related issues again, though...

**Comment by debrouxl** [comment]
Fixed, I have created a more focused issue as a followup.
